export const teachersArray = [
    {
        id: "1",
        name: "Sabrina",
        phone_number: "55(85)988776655",
        email: "email@email.com",
        role: "Admin",
    },
    {
        id: "2",
        name: "Sabrina",
        phone_number: "55(85)988776655",
        email: "email@email.com",
        role: "Admin",
    },
    {
        id: "3",
        name: "Sabrina",
        phone_number: "55(85)988776655",
        email: "email@email.com",
        role: "Professora",
    },
    {
        id: "4",
        name: "Sabrina",
        phone_number: "55(85)988776655",
        email: "email@email.com",
        role: "Professora",
    },
    {
        id: "5",
        name: "Sabrina",
        phone_number: "55(85)988776655",
        email: "email@email.com",
        role: "Admin",
    },
    {
        id: "6",
        name: "Sabrina",
        phone_number: "55(85)988776655",
        email: "email@email.com",
        role: "Professora",
    },
    {
        id: "7",
        name: "Sabrina",
        phone_number: "55(85)988776655",
        email: "email@email.com",
        role: "Professora",
    },
    {
        id: "8",
        name: "Sabrina",
        phone_number: "55(85)988776655",
        email: "email@email.com",
        role: "Professora",
    },
    {
        id: "9",
        name: "Sabrina",
        phone_number: "55(85)988776655",
        email: "email@email.com",
        role: "Professora",
    },
    {
        id: "10",
        name: "Sabrina",
        phone_number: "55(85)988776655",
        email: "email@email.com",
        role: "Professora",
    },
]